const instrumentsList = [
    {
        name: 'Pressure Gauge',
        category: 'Pressure Calibration',
        price: 5000,
        currency: 'PKR',
    },
    {
        name: 'Vacuum Gauge',
        category: 'Pressure Calibration',
        price: 4500,
        currency: 'PKR',
    },
    {
        name: 'Compound Gauge',
        category: 'Pressure Calibration',
        price: 5200,
        currency: 'PKR',
    },
    {
        name: 'Pressure Transmitter',
        category: 'Pressure Calibration',
        price: 7500,
        currency: 'PKR',
    },
    {
        name: 'Pressure Calibrator',
        category: 'Pressure Calibration',
        price: 8500,
        currency: 'PKR',
    },
    {
        name: 'Pressure Transducer',
        category: 'Pressure Calibration',
        price: 6900,
        currency: 'PKR',
    },
    {
        name: 'Pressure Switch',
        category: 'Pressure Calibration',
        price: 6000,
        currency: 'PKR',
    },
    {
        name: 'Pressure Chart Recorder',
        category: 'Pressure Calibration',
        price: 9000,
        currency: 'PKR',
    },
    {
        name: 'Dead Weight Tester',
        category: 'Pressure Calibration',
        price: 11000,
        currency: 'PKR',
    },
    {
        name: 'Differential Pressure Gauge',
        category: 'Pressure Calibration',
        price: 7800,
        currency: 'PKR',
    },
    {
        name: 'Anemometer',
        category: 'Pressure Calibration',
        price: 4000,
        currency: 'PKR',
    },
    {
        name: 'Air Velocity Meter',
        category: 'Pressure Calibration',
        price: 4300,
        currency: 'PKR',
    },
    {
        name: 'Barometer',
        category: 'Pressure Calibration',
        price: 3900,
        currency: 'PKR',
    },
    {
        name: 'Digital Pressure Gauge',
        category: 'Pressure Calibration',
        price: 8000,
        currency: 'PKR',
    },
    {
        name: 'Flow Transmitter',
        category: 'Pressure Calibration',
        price: 9100,
        currency: 'PKR',
    },
    {
        name: 'Gram Gauge',
        category: 'Pressure Calibration',
        price: 3100,
        currency: 'PKR',
    },
    {
        name: 'High Pressure Gauge',
        category: 'Pressure Calibration',
        price: 8200,
        currency: 'PKR',
    },
    {
        name: 'Hook Gauges',
        category: 'Pressure Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Low Pressure Gauge',
        category: 'Pressure Calibration',
        price: 4800,
        currency: 'PKR',
    },
    {
        name: 'Manometer',
        category: 'Pressure Calibration',
        price: 3600,
        currency: 'PKR',
    },
    {
        name: 'Air/Mass Flow Meter',
        category: 'Pressure Calibration',
        price: 9700,
        currency: 'PKR',
    },
    {
        name: 'Oscilloscope',
        category: 'Pressure Calibration',
        price: 12000,
        currency: 'PKR',
    },
    {
        name: 'Pressure Recorder',
        category: 'Pressure Calibration',
        price: 9100,
        currency: 'PKR',
    },
    {
        name: 'RPM Meter',
        category: 'Pressure Calibration',
        price: 4300,
        currency: 'PKR',
    },
    {
        name: 'Rubber Hardness Tester',
        category: 'Pressure Calibration',
        price: 7500,
        currency: 'PKR',
    },
    {
        name: 'Speed Meter',
        category: 'Pressure Calibration',
        price: 6400,
        currency: 'PKR',
    },
    {
        name: 'Turbine Meter',
        category: 'Pressure Calibration',
        price: 9800,
        currency: 'PKR',
    },
    {
        name: 'Vacuum Switch',
        category: 'Pressure Calibration',
        price: 5200,
        currency: 'PKR',
    },
    {
        name: 'NDT Non Destructive Testing',
        category: 'Pressure Calibration',
        price: 13400,
        currency: 'PKR',
    },
    {
        name: 'Medical Device Manufacturing Plant Mass Flow Instrument',
        category: 'Pressure Calibration',
        price: 15700,
        currency: 'PKR',
    },
    {
        name: 'Temperature Controller / Indicator',
        category: 'Temperature Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Temperature Sensor (RTD, Thermocouple)',
        category: 'Temperature Calibration',
        price: 3200,
        currency: 'PKR',
    },
    {
        name: 'Temperature Transmitter',
        category: 'Temperature Calibration',
        price: 7300,
        currency: 'PKR',
    },
    {
        name: 'Temperature Calibrator (Liquid & Dry Block)',
        category: 'Temperature Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Temperature Recorder (Chart/Digital)',
        category: 'Temperature Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Thermo Switch / Thermostat',
        category: 'Temperature Calibration',
        price: 4100,
        currency: 'PKR',
    },
    {
        name: 'Thermometer (Glass/Digital/Wet, Dry & IR)',
        category: 'Temperature Calibration',
        price: 2900,
        currency: 'PKR',
    },
    {
        name: 'Hot Air Oven',
        category: 'Temperature Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Muffle Furnace',
        category: 'Temperature Calibration',
        price: 8400,
        currency: 'PKR',
    },
    {
        name: 'Water Bath',
        category: 'Temperature Calibration',
        price: 4900,
        currency: 'PKR',
    },
    {
        name: 'Incubator',
        category: 'Temperature Calibration',
        price: 7800,
        currency: 'PKR',
    },
    {
        name: 'Refrigerator',
        category: 'Temperature Calibration',
        price: 12400,
        currency: 'PKR',
    },
    {
        name: 'Deep Freezer',
        category: 'Temperature Calibration',
        price: 13200,
        currency: 'PKR',
    },
    {
        name: 'Analog Gauge',
        category: 'Temperature Calibration',
        price: 3200,
        currency: 'PKR',
    },
    {
        name: 'Bi-Metal Thermocouple',
        category: 'Temperature Calibration',
        price: 6200,
        currency: 'PKR',
    },
    {
        name: 'Digital Thermometer',
        category: 'Temperature Calibration',
        price: 3600,
        currency: 'PKR',
    },
    {
        name: 'Digital Temperature Indicator',
        category: 'Temperature Calibration',
        price: 4100,
        currency: 'PKR',
    },
    {
        name: 'Dry Block',
        category: 'Temperature Calibration',
        price: 7400,
        currency: 'PKR',
    },
    {
        name: 'Data Logger',
        category: 'Temperature Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Furnace',
        category: 'Temperature Calibration',
        price: 13400,
        currency: 'PKR',
    },
    {
        name: 'Freezer',
        category: 'Temperature Calibration',
        price: 13800,
        currency: 'PKR',
    },
    {
        name: 'Glass Thermometer',
        category: 'Temperature Calibration',
        price: 2500,
        currency: 'PKR',
    },
    {
        name: 'Heating Bath / Block',
        category: 'Temperature Calibration',
        price: 8500,
        currency: 'PKR',
    },
    {
        name: 'Infrared Thermometer',
        category: 'Temperature Calibration',
        price: 4500,
        currency: 'PKR',
    },
    {
        name: 'Oven',
        category: 'Temperature Calibration',
        price: 8700,
        currency: 'PKR',
    },
    {
        name: 'Oil Bath',
        category: 'Temperature Calibration',
        price: 6900,
        currency: 'PKR',
    },
    {
        name: 'PRT',
        category: 'Temperature Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Partial Immersion Thermometer',
        category: 'Temperature Calibration',
        price: 3600,
        currency: 'PKR',
    },
    {
        name: 'Pyrometer',
        category: 'Temperature Calibration',
        price: 9800,
        currency: 'PKR',
    },
    {
        name: 'RTD Thermometer',
        category: 'Temperature Calibration',
        price: 6100,
        currency: 'PKR',
    },
    {
        name: 'Sterilizer',
        category: 'Temperature Calibration',
        price: 14200,
        currency: 'PKR',
    },
    {
        name: 'Surface Thermometer',
        category: 'Temperature Calibration',
        price: 4300,
        currency: 'PKR',
    },
    {
        name: 'Thermocouple Thermometer',
        category: 'Temperature Calibration',
        price: 5100,
        currency: 'PKR',
    },
    {
        name: 'Thermocouple Probe',
        category: 'Temperature Calibration',
        price: 2700,
        currency: 'PKR',
    },
    {
        name: 'Temperature Gauge',
        category: 'Temperature Calibration',
        price: 3200,
        currency: 'PKR',
    },
    {
        name: 'Temperature Switches',
        category: 'Temperature Calibration',
        price: 4500,
        currency: 'PKR',
    },
    {
        name: 'Temperature Transducer',
        category: 'Temperature Calibration',
        price: 7200,
        currency: 'PKR',
    },
    {
        name: 'Thermistor Probe',
        category: 'Temperature Calibration',
        price: 2600,
        currency: 'PKR',
    },
    {
        name: 'Temperature Pen Recorder',
        category: 'Temperature Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Thermo-hygrograph',
        category: 'Temperature Calibration',
        price: 9400,
        currency: 'PKR',
    },
    {
        name: 'Thermo-hygrometer',
        category: 'Temperature Calibration',
        price: 7300,
        currency: 'PKR',
    },
    {
        name: 'Temperature & Humidity Meter',
        category: 'Temperature Calibration',
        price: 8300,
        currency: 'PKR',
    },
    {
        name: 'Total-Immersion Glass Thermometer',
        category: 'Temperature Calibration',
        price: 3000,
        currency: 'PKR',
    },
    {
        name: 'Digital Electromagnetic Type Flow Meter',
        category: 'Flow Meter Calibration',
        price: 12000,
        currency: 'PKR',
    },
    {
        name: 'Turbine Type Flow Meter',
        category: 'Flow Meter Calibration',
        price: 11500,
        currency: 'PKR',
    },
    {
        name: 'Thermal Mass Flow Meter',
        category: 'Flow Meter Calibration',
        price: 10800,
        currency: 'PKR',
    },
    {
        name: 'Vortex Type Flow Meter',
        category: 'Flow Meter Calibration',
        price: 9900,
        currency: 'PKR',
    },
    {
        name: 'Calories Mass Flow Meter',
        category: 'Flow Meter Calibration',
        price: 10500,
        currency: 'PKR',
    },
    {
        name: 'Glass Rota Meter',
        category: 'Flow Meter Calibration',
        price: 4700,
        currency: 'PKR',
    },
    {
        name: 'Orifice Type Flow Meter',
        category: 'Flow Meter Calibration',
        price: 9300,
        currency: 'PKR',
    },
    {
        name: 'Weighing Balance',
        category: 'Mechanical Calibration',
        price: 8600,
        currency: 'PKR',
    },
    {
        name: 'Weights/Weight Box',
        category: 'Mechanical Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Cable Tension Meter',
        category: 'Mechanical Calibration',
        price: 7600,
        currency: 'PKR',
    },
    {
        name: 'Durometer',
        category: 'Mechanical Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Force Gauge',
        category: 'Mechanical Calibration',
        price: 7800,
        currency: 'PKR',
    },
    {
        name: 'Gram Gauge',
        category: 'Mechanical Calibration',
        price: 3200,
        currency: 'PKR',
    },
    {
        name: 'Hardness Machine',
        category: 'Mechanical Calibration',
        price: 14200,
        currency: 'PKR',
    },
    {
        name: 'Hardness Meter',
        category: 'Mechanical Calibration',
        price: 11400,
        currency: 'PKR',
    },
    {
        name: 'Load Cell',
        category: 'Mechanical Calibration',
        price: 10400,
        currency: 'PKR',
    },
    {
        name: 'Push/Pull Gauge',
        category: 'Mechanical Calibration',
        price: 6500,
        currency: 'PKR',
    },
    {
        name: 'Pocket Balance',
        category: 'Mechanical Calibration',
        price: 2900,
        currency: 'PKR',
    },
    {
        name: 'RPM Meter',
        category: 'Mechanical Calibration',
        price: 4500,
        currency: 'PKR',
    },
    {
        name: 'Rubber Hardness Tester',
        category: 'Mechanical Calibration',
        price: 7100,
        currency: 'PKR',
    },
    {
        name: 'Spring Balance',
        category: 'Mechanical Calibration',
        price: 5200,
        currency: 'PKR',
    },
    {
        name: 'Speed Indicator',
        category: 'Mechanical Calibration',
        price: 6500,
        currency: 'PKR',
    },
    {
        name: 'Stroboscope',
        category: 'Mechanical Calibration',
        price: 12400,
        currency: 'PKR',
    },
    {
        name: 'Tension Gauge',
        category: 'Mechanical Calibration',
        price: 5200,
        currency: 'PKR',
    },
    {
        name: 'Tachometer',
        category: 'Mechanical Calibration',
        price: 4500,
        currency: 'PKR',
    },
    {
        name: 'Torque Driver',
        category: 'Mechanical Calibration',
        price: 8100,
        currency: 'PKR',
    },
    {
        name: 'Torque Checker',
        category: 'Mechanical Calibration',
        price: 9300,
        currency: 'PKR',
    },
    {
        name: 'Torque Dial',
        category: 'Mechanical Calibration',
        price: 7100,
        currency: 'PKR',
    },
    {
        name: 'Torque Gauge',
        category: 'Mechanical Calibration',
        price: 6700,
        currency: 'PKR',
    },
    {
        name: 'Torque Wrench',
        category: 'Mechanical Calibration',
        price: 7500,
        currency: 'PKR',
    },
    {
        name: 'Standard Weights',
        category: 'Mechanical Calibration',
        price: 4200,
        currency: 'PKR',
    },
    {
        name: 'Digital Multimeter',
        category: 'Electrical Calibration',
        price: 5700,
        currency: 'PKR',
    },
    {
        name: 'Multi-Function Calibrator',
        category: 'Electrical Calibration',
        price: 12600,
        currency: 'PKR',
    },
    {
        name: 'Clamp Meter',
        category: 'Electrical Calibration',
        price: 6400,
        currency: 'PKR',
    },
    {
        name: 'Ammeter / Voltmeter',
        category: 'Electrical Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Loop Calibrator',
        category: 'Electrical Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Insulation Tester',
        category: 'Electrical Calibration',
        price: 8700,
        currency: 'PKR',
    },
    {
        name: 'Tachometer (non-contact)',
        category: 'Electrical Calibration',
        price: 7300,
        currency: 'PKR',
    },
    {
        name: 'AC/DC Power Supply',
        category: 'Electrical Calibration',
        price: 10200,
        currency: 'PKR',
    },
    {
        name: 'Analogue & Digital Meter',
        category: 'Electrical Calibration',
        price: 7800,
        currency: 'PKR',
    },
    {
        name: 'Earth Tester',
        category: 'Electrical Calibration',
        price: 9300,
        currency: 'PKR',
    },
    {
        name: 'Decade Resistance Box',
        category: 'Electrical Calibration',
        price: 7400,
        currency: 'PKR',
    },
    {
        name: 'Capacitance Box',
        category: 'Electrical Calibration',
        price: 5400,
        currency: 'PKR',
    },
    {
        name: 'Current Probe',
        category: 'Electrical Calibration',
        price: 6200,
        currency: 'PKR',
    },
    {
        name: 'Current Clamp',
        category: 'Electrical Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Energy Meter',
        category: 'Electrical Calibration',
        price: 8900,
        currency: 'PKR',
    },
    {
        name: 'Function Generator',
        category: 'Electrical Calibration',
        price: 9600,
        currency: 'PKR',
    },
    {
        name: 'Frequency Meter',
        category: 'Electrical Calibration',
        price: 6400,
        currency: 'PKR',
    },
    {
        name: 'Frequency Counter',
        category: 'Electrical Calibration',
        price: 7700,
        currency: 'PKR',
    },
    {
        name: 'High Voltage Generator',
        category: 'Electrical Calibration',
        price: 12400,
        currency: 'PKR',
    },
    {
        name: 'High Voltage Probe',
        category: 'Electrical Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Hi Pot Tester',
        category: 'Electrical Calibration',
        price: 10400,
        currency: 'PKR',
    },
    {
        name: 'Induction Box',
        category: 'Electrical Calibration',
        price: 6700,
        currency: 'PKR',
    },
    {
        name: 'LCR Meter',
        category: 'Electrical Calibration',
        price: 7900,
        currency: 'PKR',
    },
    {
        name: 'Logger',
        category: 'Electrical Calibration',
        price: 5700,
        currency: 'PKR',
    },
    {
        name: 'Multi Function Meter',
        category: 'Electrical Calibration',
        price: 8700,
        currency: 'PKR',
    },
    {
        name: 'Megaohmeter',
        category: 'Electrical Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Milliohmeter',
        category: 'Electrical Calibration',
        price: 6700,
        currency: 'PKR',
    },
    {
        name: 'Oscilloscope',
        category: 'Electrical Calibration',
        price: 9500,
        currency: 'PKR',
    },
    {
        name: 'Phase Detector',
        category: 'Electrical Calibration',
        price: 8500,
        currency: 'PKR',
    },
    {
        name: 'Phase Indicator',
        category: 'Electrical Calibration',
        price: 7800,
        currency: 'PKR',
    },
    {
        name: 'Power Meter',
        category: 'Electrical Calibration',
        price: 11300,
        currency: 'PKR',
    },
    {
        name: 'Power Supply Functions',
        category: 'Electrical Calibration',
        price: 9700,
        currency: 'PKR',
    },
    {
        name: 'Resistivity Meter',
        category: 'Electrical Calibration',
        price: 12700,
        currency: 'PKR',
    },
    {
        name: 'RCD Meter',
        category: 'Electrical Calibration',
        price: 8200,
        currency: 'PKR',
    },
    {
        name: 'System Control',
        category: 'Electrical Calibration',
        price: 14200,
        currency: 'PKR',
    },
    {
        name: 'Scope Meter',
        category: 'Electrical Calibration',
        price: 13400,
        currency: 'PKR',
    },
    {
        name: 'Timer',
        category: 'Electrical Calibration',
        price: 4700,
        currency: 'PKR',
    },
    {
        name: 'Volt Meter',
        category: 'Electrical Calibration',
        price: 6100,
        currency: 'PKR',
    },
    {
        name: 'Vernier Caliper',
        category: 'Precision Calibration',
        price: 4900,
        currency: 'PKR',
    },
    {
        name: 'Micrometer',
        category: 'Precision Calibration',
        price: 4200,
        currency: 'PKR',
    },
    {
        name: 'Dial Gauge(Plunger/Lever/Bore)',
        category: 'Precision Calibration',
        price: 5300,
        currency: 'PKR',
    },
    {
        name: 'Measuring Tape',
        category: 'Precision Calibration',
        price: 2600,
        currency: 'PKR',
    },
    {
        name: 'V Block',
        category: 'Precision Calibration',
        price: 4800,
        currency: 'PKR',
    },
    {
        name: 'Steel Ruler',
        category: 'Precision Calibration',
        price: 2400,
        currency: 'PKR',
    },
    {
        name: 'Bore Gauges',
        category: 'Precision Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Bevel Protractor',
        category: 'Precision Calibration',
        price: 3700,
        currency: 'PKR',
    },
    {
        name: 'Bubble Level Gauge',
        category: 'Precision Calibration',
        price: 3400,
        currency: 'PKR',
    },
    {
        name: 'Carpenter Tape',
        category: 'Precision Calibration',
        price: 4100,
        currency: 'PKR',
    },
    {
        name: 'Circumferential Tape',
        category: 'Precision Calibration',
        price: 3900,
        currency: 'PKR',
    },
    {
        name: 'Caliper Gauge',
        category: 'Precision Calibration',
        price: 4600,
        currency: 'PKR',
    },
    {
        name: 'Coating & Thickness Gauges',
        category: 'Precision Calibration',
        price: 6400,
        currency: 'PKR',
    },
    {
        name: 'Check Master',
        category: 'Precision Calibration',
        price: 7200,
        currency: 'PKR',
    },
    {
        name: 'Caliper Checker',
        category: 'Precision Calibration',
        price: 5900,
        currency: 'PKR',
    },
    {
        name: 'Crimping Tools',
        category: 'Precision Calibration',
        price: 5100,
        currency: 'PKR',
    },
    {
        name: 'Carpenter’s Level Gauge',
        category: 'Precision Calibration',
        price: 5300,
        currency: 'PKR',
    },
    {
        name: 'Dial Test Indicator',
        category: 'Precision Calibration',
        price: 6800,
        currency: 'PKR',
    },
    {
        name: 'Dial Vernier Caliper',
        category: 'Precision Calibration',
        price: 5300,
        currency: 'PKR',
    },
    {
        name: 'Digital Caliper',
        category: 'Precision Calibration',
        price: 6400,
        currency: 'PKR',
    },
    {
        name: 'Digital Thickness Gauge',
        category: 'Precision Calibration',
        price: 7100,
        currency: 'PKR',
    },
    {
        name: 'Feeler Gauge',
        category: 'Precision Calibration',
        price: 2800,
        currency: 'PKR',
    },
    {
        name: 'Gauge Blocks',
        category: 'Precision Calibration',
        price: 9200,
        currency: 'PKR',
    },
    {
        name: 'Height Gauge',
        category: 'Precision Calibration',
        price: 8500,
        currency: 'PKR',
    },
    {
        name: 'Inside Micrometer',
        category: 'Precision Calibration',
        price: 7400,
        currency: 'PKR',
    },
    {
        name: 'Plunger Dial Gauge',
        category: 'Precision Calibration',
        price: 5700,
        currency: 'PKR',
    },
    {
        name: 'Screw Pitch Gauge',
        category: 'Precision Calibration',
        price: 3000,
        currency: 'PKR',
    },
    {
        name: 'Slip Gauge',
        category: 'Precision Calibration',
        price: 8800,
        currency: 'PKR',
    },
    {
        name: 'Straight Edge Ruler',
        category: 'Precision Calibration',
        price: 2600,
        currency: 'PKR',
    },
    {
        name: 'Thread Gauge',
        category: 'Precision Calibration',
        price: 3200,
        currency: 'PKR',
    },
    {
        name: 'Thickness Gauge',
        category: 'Precision Calibration',
        price: 4900,
        currency: 'PKR',
    },
    {
        name: 'Dry Heat Sterilizer',
        category: 'Thermal Mapping / Validation',
        price: 12000,
        currency: 'PKR',
    },
    {
        name: 'Auto Clave',
        category: 'Thermal Mapping / Validation',
        price: 15000,
        currency: 'PKR',
    },
    {
        name: 'Steam Sterilizer',
        category: 'Thermal Mapping / Validation',
        price: 16500,
        currency: 'PKR',
    },
    {
        name: 'Oven',
        category: 'Thermal Mapping / Validation',
        price: 18000,
        currency: 'PKR',
    },
    {
        name: 'Stability Chamber',
        category: 'Thermal Mapping / Validation',
        price: 24000,
        currency: 'PKR',
    },
    {
        name: 'Humidity Chamber',
        category: 'Thermal Mapping / Validation',
        price: 22000,
        currency: 'PKR',
    },
    {
        name: 'Incubator',
        category: 'Thermal Mapping / Validation',
        price: 13000,
        currency: 'PKR',
    },
    {
        name: 'Tray Dryer',
        category: 'Thermal Mapping / Validation',
        price: 19000,
        currency: 'PKR',
    },
    {
        name: 'Warehouse',
        category: 'Thermal Mapping / Validation',
        price: 30000,
        currency: 'PKR',
    },
    {
        name: 'Cold Room',
        category: 'Thermal Mapping / Validation',
        price: 35000,
        currency: 'PKR',
    },
];

export default instrumentsList;
